[project]
name = "nhsjc25-codespaces"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "csvkit>=2.1.0",
    "requests>=2.32.0",
    "beautifulsoup4>=4.12.0",
]
